version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
  redis:
    image: redis:alpine
    tty: true
    restart: always
    container_name: redis
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - ./cache:/data
    logging:
        options:
            max-size: "5m"
    command: redis-server --appendonly yes
    ports:
        - 6379:6379
            
  mariadb:
    image: mariadb:10.3.32
    restart: always
    volumes:
    - ./db:/var/lib/mysql
    ports:
    - 127.0.0.1:3307:3307
    environment:
        TZ: "Asia/Tehran"
        MYSQL_ALLOW_EMPTY_PASSWORD: "no"
        MYSQL_USER: 'yiidocker'
        MYSQL_PASSWORD: 'yiidocker'
        MYSQL_ROOT_PASSWORD: "root"
        MYSQL_DATABASE: 'excelpanel'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080


volumes:
    mariadb: